#!/bin/bash

# Download and install the java kernel
curl -L https://github.com/SpencerPark/IJava/releases/download/v1.3.0/ijava-1.3.0.zip > ijava-kernel.zip
unzip ijava-kernel.zip -d ijava-kernel \
  && cd ijava-kernel \
  && python install.py --sys-prefix

# Cleanup
cd ..
rm ijava-kernel.zip
rm -r ijava-kernel

# Download and install the scala kernel
curl -Lo coursier https://git.io/coursier-cli
chmod +x coursier
./coursier launch --fork almond:0.10.8 --scala 2.13.3 -- --install

# Cleanup
rm coursier
