name: Python Test

on:
  pull_request:
    branches:
      - main
    paths:
      - converter/**
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.9"
  NODE_VERSION: "18"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: converter

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      - name: Install dependencies
        run: pip install pytest flake8
      - name: Lint
        run: flake8
      - name: Test
        run: pytest
