name: Trigger Deployment to LucienZhang.github.io

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_ACCESS_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'LucienZhang',
              repo: 'LucienZhang.github.io',
              workflow_id: 'deploy_gh_page.yml',
              ref: 'main',
            })
